adds logs when push-vote panics with invalid vote-index (#19485) (#19521)
In order to debug this panic on the clusters:

  panicked at 'assertion failed: (vote_index as usize) <
  MAX_LOCKOUT_HISTORY', core/src/cluster_info.rs:1012:9

(cherry picked from commit d7051b0d215ec68a39ddee2dfe11df1b28a3eb94)

Co-authored-by: behzad nouri <behzadnouri@gmail.com>