Revert: Bump console from 0.15.0 to 0.15.5 (#31289)
  commit 4e3300e7d66a12d4fd377704d1b5c202897d08eb
  Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
  Date:   Thu Apr 20 15:40:14 2023 -0700

      Bump console from 0.15.0 to 0.15.5 (#31289)

      Bumps [console](https://github.com/console-rs/console) from 0.15.0 to 0.15.5.
      - [Release notes](https://github.com/console-rs/console/releases)
      - [Changelog](https://github.com/console-rs/console/blob/master/CHANGELOG.md)
      - [Commits](console-rs/console@0.15.0...0.15.5)

      ---
      updated-dependencies:
      - dependency-name: console
        dependency-type: direct:production
        update-type: version-update:semver-patch
      ...

      Signed-off-by: dependabot[bot] <support@github.com>

Windows build is broken with the following error:

  Compiling solana-genesis-utils v1.16.0 (D:\a\solana\solana\genesis-utils)
  error[E0432]: unresolved import `winapi::um::winuser`
     --> install\src\command.rs:385:17
      |
  385 |             um::winuser::{
      |                 ^^^^^^^ could not find `winuser` in `um`

  For more information about this error, try `rustc --explain E0432`.

https://github.com/solana-labs/solana/actions/runs/4759519915/jobs/8458877323